export const useIcons = () => {
  const cashAccountIcons = [
    { label: '', value: 'simple-icons:revolut' },
    { label: '', value: 'simple-icons:wise' },
    { label: '', value: 'simple-icons:monzo' },
    { label: '', value: 'simple-icons:n26' },
    { label: '', value: 'simple-icons:bunq' },
    { label: '', value: 'simple-icons:cashapp' },
    { label: '', value: 'simple-icons:bitcoin' },
    { label: '', value: 'simple-icons:nubank' },
    { label: '', value: 'simple-icons:starlingbank' },
    { label: '', value: 'simple-icons:bankofamerica' },
    { label: '', value: 'simple-icons:deutschebank' },

  ]

  const cryptoIcons = [
    { label: '', value: 'simple-icons:binance' },
    { label: '', value: 'tabler:brand-coinbase' },
    { label: '', value: 'arcticons:kraken' },
    { label: '', value: 'material-symbols:currency-bitcoin' },
    { label: '', value: 'mdi:bitcoin' },
    { label: '', value: 'tabler:coin-bitcoin' },
    { label: '', value: 'simple-icons:ethereum' },
    { label: '', value: 'tabler:currency-ethereum' },
  ]

  const categoryIcons = [
    { label: '', value: 'tabler:baby-carriage' },
    { label: '', value: 'tabler:caravan' },
    { label: '', value: 'tabler:briefcase' },
    { label: '', value: 'tabler:car' },
    { label: '', value: 'tabler:social' },
    { label: '', value: 'tabler:users' },
    { label: '', value: 'tabler:barbell' },
    { label: '', value: 'tabler:geometry' },
    { label: '', value: 'tabler:presentation-analytics' },
    { label: '', value: 'tabler:music' },
    { label: '', value: 'tabler:bus' },
    { label: '', value: 'tabler:bus-stop' },
    { label: '', value: 'tabler:power' },
    { label: '', value: 'tabler:music' },
    { label: '', value: 'tabler:carrot' },
    { label: '', value: 'tabler:apple' },
    { label: '', value: 'tabler:baguette' },
    { label: '', value: 'tabler:pizza' },
    { label: '', value: 'tabler:cookie' },
    { label: '', value: 'tabler:eggs' },
    { label: '', value: 'tabler:fish' },
    { label: '', value: 'tabler:lollipop' },
    { label: '', value: 'tabler:sausage' },
    { label: '', value: 'tabler:meat' },
    { label: '', value: 'tabler:fish-bone' },
    { label: '', value: 'tabler:grill' },
    { label: '', value: 'tabler:ice-cream-2' },
    { label: '', value: 'tabler:bone' },
    { label: '', value: 'tabler:cake' },
    { label: '', value: 'tabler:gift' },
    { label: '', value: 'tabler:christmas-tree' },
    { label: '', value: 'tabler:ball-american-football' },
    { label: '', value: 'tabler:sport-billard' },
    { label: '', value: 'tabler:shirt-sport' },
    { label: '', value: 'tabler:ball-football' },
    { label: '', value: 'tabler:ball-basketball' },
    { label: '', value: 'tabler:ball-tennis' },
    { label: '', value: 'tabler:bath' },
    { label: '', value: 'tabler:beach' },
    { label: '', value: 'tabler:ballon' },
    { label: '', value: 'tabler:backpack' },
    { label: '', value: 'tabler:candle' },
    { label: '', value: 'tabler:rainbow' },
    { label: '', value: 'tabler:cloud' },
    { label: '', value: 'tabler:droplet' },
    { label: '', value: 'tabler:glass' },
    { label: '', value: 'tabler:glass-full' },
    { label: '', value: 'tabler:cloud-rain' },
    { label: '', value: 'tabler:basket' },
    { label: '', value: 'tabler:graph' },
    { label: '', value: 'tabler:leaf' },
    { label: '', value: 'tabler:flask' },
    { label: '', value: 'tabler:medical-cross' },
    { label: '', value: 'tabler:pill' },
    { label: '', value: 'tabler:heart' },
    { label: '', value: 'tabler:heartbeat' },
    { label: '', value: 'tabler:ghost' },
    { label: '', value: 'tabler:flask' },
    { label: '', value: 'tabler:device-sd-card' },
    { label: '', value: 'tabler:camera' },
    { label: '', value: 'tabler:math-avg' },
    { label: '', value: 'tabler:camera-selfie' },
    { label: '', value: 'tabler:ruler' },
    { label: '', value: 'tabler:moneybag' },
    { label: '', value: 'tabler:cash' },
    { label: '', value: 'tabler:cash-banknote' },
    { label: '', value: 'tabler:bike' },
    { label: '', value: 'tabler:motorbike' },
    { label: '', value: 'tabler:moped' },
    { label: '', value: 'tabler:scooter' },
    { label: '', value: 'tabler:mailbox' },
    { label: '', value: 'tabler:pig-money' },
    { label: '', value: 'tabler:skull' },
    { label: '', value: 'tabler:armchair' },
    { label: '', value: 'tabler:armchair-2' },
    { label: '', value: 'tabler:paint' },
    { label: '', value: 'tabler:clothes-rack' },
    { label: '', value: 'tabler:shirt' },
    { label: '', value: 'tabler:shoe' },
    { label: '', value: 'tabler:chef-hat' },
    { label: '', value: 'tabler:address-book' },
    { label: '', value: 'tabler:masks-theater' },
    { label: '', value: 'tabler:book' },
    { label: '', value: 'tabler:book-2' },
    { label: '', value: 'tabler:pumpkin-scary' },
    { label: '', value: 'tabler:bolt' },
    { label: '', value: 'tabler:home' },
    { label: '', value: 'tabler:home-bolt' },
    { label: '', value: 'tabler:server-bolt' },
    { label: '', value: 'tabler:device-mobile' },
    { label: '', value: 'tabler:device-laptop' },
    { label: '', value: 'tabler:device-desktop' },
    { label: '', value: 'tabler:device-tv' },
    { label: '', value: 'tabler:devices' },
    { label: '', value: 'tabler:device-gamepad' },
    { label: '', value: 'tabler:device-gamepad-2' },
    { label: '', value: 'tabler:device-floppy' },
    { label: '', value: 'tabler:telescope' },
    { label: '', value: 'tabler:compass' },
    { label: '', value: 'tabler:thumb-up' },
    { label: '', value: 'tabler:thumb-down' },
    { label: '', value: 'tabler:ribbon-health' },
    { label: '', value: 'tabler:health-recognition' },
    { label: '', value: 'tabler:walk' },
    { label: '', value: 'tabler:run' },
    { label: '', value: 'tabler:building' },
    { label: '', value: 'tabler:building-skyscraper' },
    { label: '', value: 'tabler:building-community' },

  ]

  const moneyIcons = [
    { label: '', value: 'tabler:wallet' },
    { label: '', value: 'tabler:report-money' },
    { label: '', value: 'tabler:moneybag' },
    { label: '', value: 'tabler:home-dollar' },
    { label: '', value: 'tabler:receipt' },
    { label: '', value: 'tabler:receipt-2' },
    { label: '', value: 'tabler:pig-money' },
    { label: '', value: 'tabler:cash' },
    { label: '', value: 'tabler:cash-banknote' },
    { label: '', value: 'tabler:building-bank' },
    { label: '', value: 'tabler:brand-mastercard' },
    { label: '', value: 'tabler:brand-visa' },
    { label: '', value: 'tabler:coin' },
    { label: '', value: 'tabler:coin-euro' },
    { label: '', value: 'tabler:coin-pound' },
    { label: '', value: 'tabler:chart-area-line' },
    { label: '', value: 'tabler:chart-bar' },
  ]

  const allIcons = [...cashAccountIcons, ...moneyIcons, ...cryptoIcons]

  const sortIcons = (icons: { label: string; value: string }[]) => {
    return icons.sort((a, b) => a.value < b.value ? -1 : 1)
  }

  return {
    allIcons: sortIcons(allIcons),
    crytpoIcons: sortIcons(cryptoIcons),
    cashAccountIcons: sortIcons(cashAccountIcons),
    moneyIcons: sortIcons(moneyIcons),
    categoryIcons: sortIcons(categoryIcons),
  }
}
